name: Beispiel
version: 1.0
main: itIsAProject.main.Main

commands:
   heal:
      description: This Command heals you!
      usage:
   removeheal:
      description: Steal the Health of others or just remove your own!
      usage:
   kit:
      description: Select a Kit to fight your enemies!
      usage:
   setspawn:
      description: Set your Spawnpoint!
      usage:
      